mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
mod day09;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;

fn main() {
    println!("\n==== DAY 01 ====");
    day01::part1::calc_total_difference();
    day01::part2::calc_similarity_score();
    println!("\n==== DAY 02 ====");
    day02::part1::sum_safe_reports();
    day02::part2::run_problem_dampener();
    println!("\n==== DAY 03 ====");
    day03::part1::print_reg_instruction_prod_sum();
    day03::part2::print_cond_instruction_prod_sum();
    println!("\n==== DAY 04 ====");
    day04::part1::solve_xmas_word_search();
    day04::part2::solve_x_mas_word_search();
    println!("\n==== DAY 05 ====");
    day05::part1::print_median_safety_sum();
    println!("\n==== DAY 06 ====");
    //
    println!("\n==== DAY 07 ====");
    day07::part1::print_calibration_total();
    println!("\n==== DAY 08 ====");
    day08::part1::print_antinode_total();
    day08::part2::print_inline_antinode_total();
    println!("\n==== DAY 09 ====");
    day09::part1::print_filesystem_checksum_value();
    println!("\n==== DAY 10 ====");
    day10::part1::print_total_trailhead_score();
    day10::part2::print_trail_area_rating();
    println!("\n==== DAY 11 ====");
    day11::part1::print_little_stone_magnitude();
    println!("\n==== DAY 12 ====");
    day12::part1::print_fence_price();
    println!("\n==== DAY 13 ====");
    day13::part1::print_lowest_claw_tokens();
    println!("\n==== DAY 14 ====");
    day14::part1::print_robot_safety_factor();
    println!("\n==== DAY 15 ====");
    day15::part1::print_lanternfish_gps_sum();
    println!("\n==== DAY 16 ====");
    println!("\n==== DAY 17 ====");
    day17::part1::print_chrono_cpu_output();
}
